### ISSUE TITLE
Not incompatible with ESP8266

### ISSUE THREAD

**Issue by georgeHayRiv** [Naguissa/DebugUtils#1]
I tried to use this library with an ESP8266 and it was listed as incompatible. After some digging I found in the library.properties file this line
architectures=avr,stm32,STM32F1
removing this line makes it work for ESP8266
Replacing the line with
architectures=*
also works
architectures=avr,stm32,STM32F1,esp8266
also works and will compile esp8266 and esp12 boards that I checked.
Can you make one of these changes to github repository?

**Comment by Naguissa** [comment]
Hello,

Yes, this is more a bare bone skeleton than a library. I'll fork it into a proper library and add it to library manager. I'll reply here when done.


Cheers!

**Comment by Naguissa** [comment]
Hello,

I've tweaked and enhanced this library, changed its name and done a request to add it to Arduino Library Manager (response may delay to one week).

You can find new version here: https://github.com/Naguissa/uDebugLib

**Comment by georgeHayRiv** [comment]
Thanks for the update and submission to Arduino.
It worked just fine on my ESP8266.
Nice to see that DEBUG_PRINT doesn't require DEBUG_PRINT2 when there are
two parameters.
I will see if I can make up another example program for you that is very
simple with some more comments in the code.

I do have one question. When using DEBUG_PRINT when DEBUG is not defined do
those lines of code eliminated a compile time? I have a lot of Strings in
the DEBUG_PRINT lines and it would nice to save that memory.

George Adams
Hay River Software LLC
N14397 380th St.
Ridgeland WI 54763
715 455-1652

**Comment by Naguissa** [comment]
I´ve not tested strings but on example you can It should, but I'll try and tell you...

**Comment by georgeHayRiv** [comment]
Attached is sketch that you might want to add to your examples. Very simple
example use uDebugLib the way I use it. Some Serial.print statements that
always are on and some that debug only. I also added extra comments to help
out beginners.

George Adams
N14397 380th St.
Ridgeland WI 54763
715 455-1652

**Comment by Naguissa** [comment]
Strings/compiler tests:

AVR: Disabling debug strings are removed.
SAMD: Disabling debug strings are removed.
ESP8266: Disabling debug strings are removed.
STM32 (F1, Maple mini): Disabling debug strings are removed.
STM32 (F3): Disabling debug strings are removed.
STM32 (F4): Disabling debug strings are removed. But warnings are shown.
ESP32: Disabling debug strings are removed.


* Note: STM32 support from Roger Clarkbourne' STM32Duino.

**Comment by Naguissa** [comment]
P.S.: Attachment is not shown, you can make a GitHub's PR or send me an email to naguissa (@) foroelectro.net

Thanks!

**Comment by georgeHayRiv** [comment]
Thanks for checking all those processors.

George Adams
Hay River Software LLC
N14397 380th St.
Ridgeland WI 54763
715 455-1652

**Comment by Naguissa** [comment]
uDebugLib is now available on Arduino's Library Manager. I'll add the example soonand create 1.0.1 release.

Merry Chrstmas!

**Comment by georgeHayRiv** [comment]
Merry Christmas to you too.
I'll be looking for an upgrade notice from the Arduino library manager.


George Adams
Hay River Software LLC
N14397 380th St.
Ridgeland WI 54763
715 455-1652
